/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DSCNFTNameInterface extends ethers.utils.Interface {
  functions: {
    "mixForChanging()": FunctionFragment;
    "exists(string)": FunctionFragment;
    "setMixForChanging(uint256)": FunctionFragment;
    "V1()": FunctionFragment;
    "mixForDeleting()": FunctionFragment;
    "importFromV1(address,uint256,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "owner()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "remove(address,uint256)": FunctionFragment;
    "setMixForDeleting(uint256)": FunctionFragment;
    "named(address,uint256)": FunctionFragment;
    "names(address,uint256)": FunctionFragment;
    "mix()": FunctionFragment;
    "_exists(string)": FunctionFragment;
    "set(address,uint256,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mixForChanging",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "exists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMixForChanging",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "V1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mixForDeleting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "importFromV1",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMixForDeleting",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "named",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "names",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mix", values?: undefined): string;
  encodeFunctionData(functionFragment: "_exists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "mixForChanging",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMixForChanging",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "V1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mixForDeleting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importFromV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMixForDeleting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "named", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "names", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mix", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_exists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "SetMixForChanging(uint256)": EventFragment;
    "SetMixForDeleting(uint256)": EventFragment;
    "Set(address,uint256,address,string)": EventFragment;
    "Remove(address,uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetMixForChanging"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMixForDeleting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Set"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Remove"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class DSCNFTName extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DSCNFTNameInterface;

  functions: {
    mixForChanging(overrides?: CallOverrides): Promise<[BigNumber]>;

    "mixForChanging()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    exists(name: string, overrides?: CallOverrides): Promise<[boolean]>;

    "exists(string)"(
      name: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setMixForChanging(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMixForChanging(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    V1(overrides?: CallOverrides): Promise<[string]>;

    "V1()"(overrides?: CallOverrides): Promise<[string]>;

    mixForDeleting(overrides?: CallOverrides): Promise<[BigNumber]>;

    "mixForDeleting()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    importFromV1(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "importFromV1(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    "isOwner()"(overrides?: CallOverrides): Promise<[boolean]>;

    remove(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "remove(address,uint256)"(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setMixForDeleting(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMixForDeleting(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    named(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "named(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    names(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "names(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    mix(overrides?: CallOverrides): Promise<[string]>;

    "mix()"(overrides?: CallOverrides): Promise<[string]>;

    _exists(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "_exists(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    set(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "set(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  mixForChanging(overrides?: CallOverrides): Promise<BigNumber>;

  "mixForChanging()"(overrides?: CallOverrides): Promise<BigNumber>;

  exists(name: string, overrides?: CallOverrides): Promise<boolean>;

  "exists(string)"(name: string, overrides?: CallOverrides): Promise<boolean>;

  setMixForChanging(
    _mix: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMixForChanging(uint256)"(
    _mix: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  V1(overrides?: CallOverrides): Promise<string>;

  "V1()"(overrides?: CallOverrides): Promise<string>;

  mixForDeleting(overrides?: CallOverrides): Promise<BigNumber>;

  "mixForDeleting()"(overrides?: CallOverrides): Promise<BigNumber>;

  importFromV1(
    nft: string,
    mateId: BigNumberish,
    name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "importFromV1(address,uint256,string)"(
    nft: string,
    mateId: BigNumberish,
    name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  remove(
    nft: string,
    mateId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "remove(address,uint256)"(
    nft: string,
    mateId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setMixForDeleting(
    _mix: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMixForDeleting(uint256)"(
    _mix: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  named(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "named(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  names(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "names(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  mix(overrides?: CallOverrides): Promise<string>;

  "mix()"(overrides?: CallOverrides): Promise<string>;

  _exists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "_exists(string)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  set(
    nft: string,
    mateId: BigNumberish,
    name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "set(address,uint256,string)"(
    nft: string,
    mateId: BigNumberish,
    name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    mixForChanging(overrides?: CallOverrides): Promise<BigNumber>;

    "mixForChanging()"(overrides?: CallOverrides): Promise<BigNumber>;

    exists(name: string, overrides?: CallOverrides): Promise<boolean>;

    "exists(string)"(name: string, overrides?: CallOverrides): Promise<boolean>;

    setMixForChanging(
      _mix: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMixForChanging(uint256)"(
      _mix: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    V1(overrides?: CallOverrides): Promise<string>;

    "V1()"(overrides?: CallOverrides): Promise<string>;

    mixForDeleting(overrides?: CallOverrides): Promise<BigNumber>;

    "mixForDeleting()"(overrides?: CallOverrides): Promise<BigNumber>;

    importFromV1(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "importFromV1(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    remove(
      nft: string,
      mateId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "remove(address,uint256)"(
      nft: string,
      mateId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMixForDeleting(
      _mix: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMixForDeleting(uint256)"(
      _mix: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    named(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "named(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    names(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "names(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    mix(overrides?: CallOverrides): Promise<string>;

    "mix()"(overrides?: CallOverrides): Promise<string>;

    _exists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "_exists(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    set(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "set(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SetMixForChanging(_mix: null): EventFilter;

    SetMixForDeleting(_mix: null): EventFilter;

    Set(
      nft: string | null,
      mateId: BigNumberish | null,
      owner: string | null,
      name: null
    ): EventFilter;

    Remove(
      nft: string | null,
      mateId: BigNumberish | null,
      owner: string | null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    mixForChanging(overrides?: CallOverrides): Promise<BigNumber>;

    "mixForChanging()"(overrides?: CallOverrides): Promise<BigNumber>;

    exists(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    "exists(string)"(
      name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMixForChanging(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMixForChanging(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    V1(overrides?: CallOverrides): Promise<BigNumber>;

    "V1()"(overrides?: CallOverrides): Promise<BigNumber>;

    mixForDeleting(overrides?: CallOverrides): Promise<BigNumber>;

    "mixForDeleting()"(overrides?: CallOverrides): Promise<BigNumber>;

    importFromV1(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "importFromV1(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    remove(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "remove(address,uint256)"(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setMixForDeleting(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMixForDeleting(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    named(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "named(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    names(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "names(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mix(overrides?: CallOverrides): Promise<BigNumber>;

    "mix()"(overrides?: CallOverrides): Promise<BigNumber>;

    _exists(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "_exists(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    set(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "set(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mixForChanging(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mixForChanging()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exists(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "exists(string)"(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setMixForChanging(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMixForChanging(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    V1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "V1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mixForDeleting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mixForDeleting()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    importFromV1(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "importFromV1(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remove(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "remove(address,uint256)"(
      nft: string,
      mateId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setMixForDeleting(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMixForDeleting(uint256)"(
      _mix: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    named(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "named(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    names(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "names(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mix(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mix()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _exists(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_exists(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    set(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "set(address,uint256,string)"(
      nft: string,
      mateId: BigNumberish,
      name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
