declare const _default: {
    isTestnet: boolean;
    chainId: number;
    contracts: {
        Mate: string;
        DogeSoundContest: string;
        Name: string;
        NameV2: string;
        Message: string;
        Image: string;
        Attributes: string;
        DogeSoundContestV2: string;
        FollowMe: string;
        Vote: string;
        Mix: string;
        KSP: string;
        NewKlayPunk: string;
        MixEmitter: string;
        DevFundToken: string;
        DevFundPool: string;
        MatesPool: string;
        Booth: string;
        BurnPool: string;
        Turntables: string;
        TurntableExtras: string;
        MatesListeners: string;
        KlayMIXListeners: string;
        KSPMIXListeners: string;
        KlayMIXListenersV2: string;
        KSPMIXListenersV2: string;
        KlayMIXLPToken: string;
        KSPMIXLPToken: string;
        Klayswap: string;
        MixPriceEstimator: string;
        CasesByKate: string;
        CasesByKatePool: string;
        AnimalsPunksV2: string;
        AnimalsPunksV2Pool: string;
        PixelCat: string;
        PixelCatPool: string;
        KLITS: string;
        KLITSPool: string;
    };
};
export default _default;
//# sourceMappingURL=Config.d.ts.map