/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITurntableExtras } from "../ITurntableExtras";

export class ITurntableExtras__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITurntableExtras {
    return new Contract(address, _abi, signerOrProvider) as ITurntableExtras;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "turntableId",
        type: "uint256",
      },
    ],
    name: "extras",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "turntableId",
        type: "uint256",
      },
      {
        name: "extra",
        type: "string",
      },
    ],
    name: "set",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "turntableId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        name: "extra",
        type: "string",
      },
    ],
    name: "Set",
    type: "event",
  },
];
