/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MateCountTransferInterface extends ethers.utils.Interface {
  functions: {
    "mate()": FunctionFragment;
    "countTransfer(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "mate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "countTransfer",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "mate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "countTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export class MateCountTransfer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MateCountTransferInterface;

  functions: {
    mate(overrides?: CallOverrides): Promise<[string]>;

    "mate()"(overrides?: CallOverrides): Promise<[string]>;

    countTransfer(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "countTransfer(address,uint256,uint256)"(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  mate(overrides?: CallOverrides): Promise<string>;

  "mate()"(overrides?: CallOverrides): Promise<string>;

  countTransfer(
    to: string,
    start: BigNumberish,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "countTransfer(address,uint256,uint256)"(
    to: string,
    start: BigNumberish,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    mate(overrides?: CallOverrides): Promise<string>;

    "mate()"(overrides?: CallOverrides): Promise<string>;

    countTransfer(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "countTransfer(address,uint256,uint256)"(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    mate(overrides?: CallOverrides): Promise<BigNumber>;

    "mate()"(overrides?: CallOverrides): Promise<BigNumber>;

    countTransfer(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "countTransfer(address,uint256,uint256)"(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    countTransfer(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "countTransfer(address,uint256,uint256)"(
      to: string,
      start: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
